name: docs

on:
  push:
    branches:
      - main
      - docs

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    # Standard drop-in approach that should work for most people.
#    - uses: ammaraskar/sphinx-action@master
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10
    - name: setup
      run: |
        sudo apt install pandoc
        pip install -r requirements.txt
        pip install -r requirements-docs.txt
        jupyter nbextension enable --py --sys-prefix ipyevents
    - name: build docs
      run: |
        cd docs/
        python ./make_script.py -d
    # Publish built docs to gh-pages branch.
    # ===============================
    - name: Commit documentation changes
      run: |
        git clone https://github.com/int-brain-lab/ONE.git --branch gh-pages --single-branch gh-pages
        cp -r docs/_build/html/* gh-pages/
        cd gh-pages
        touch .nojekyll
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update documentation" -a || true
        # The above command will fail if no changes were present, so we ignore
        # that.
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        directory: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
    # ===============================
