# Reference for this action:
#   https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries
name: Publish to PyPI

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read

jobs:
  deploy:
    name: Build and publish Python distributions to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel

      - name: Build package
        run: python setup.py sdist bdist_wheel

      - name: Publish package
        # GitHub recommends pinning 3rd party actions to a commit SHA.
        uses: pypa/gh-action-pypi-publish@37f50c210e3d2f9450da2cd423303d6a14a6e29f
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
